name: Build and Deploy Docker Image to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Find projects
        shell: bash
        run: |
          set -e

          # Najdi test csproj v Levelstat_test
          TEST_CSPROJ=$(find ./Levelstat_test -name "*.csproj" | head -n 1)
          if [ -z "$TEST_CSPROJ" ]; then
            echo "ERROR: No test .csproj found under ./Levelstat_test"
            exit 1
          fi
          echo "TEST_CSPROJ=$TEST_CSPROJ" >> $GITHUB_ENV

          # Najdi app csproj v naloga2 (ignoriraj morebitne *test* projekte)
          APP_CSPROJ=$(find ./naloga2 -name "*.csproj" ! -iname "*test*" | head -n 1)
          if [ -z "$APP_CSPROJ" ]; then
            echo "ERROR: No app .csproj found under ./naloga2"
            exit 1
          fi
          echo "APP_CSPROJ=$APP_CSPROJ" >> $GITHUB_ENV

          echo "Found APP:  $APP_CSPROJ"
          echo "Found TEST: $TEST_CSPROJ"

      - name: Restore (App)
        run: dotnet restore "${{ env.APP_CSPROJ }}"

      - name: Restore (Tests)
        run: dotnet restore "${{ env.TEST_CSPROJ }}"

      - name: Build (App)
        run: dotnet build "${{ env.APP_CSPROJ }}" -c Release --no-restore

      - name: Build (Tests)
        run: dotnet build "${{ env.TEST_CSPROJ }}" -c Release --no-restore

      - name: Test
        run: dotnet test "${{ env.TEST_CSPROJ }}" -c Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: TestResults/*.trx
          reporter: dotnet-trx

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./naloga2/LevelStat_AlexNesovic
          file: ./naloga2/Dockerfile
          push: true
          tags: |
            alexnesovic/levelstat_alexnesovic:latest
            alexnesovic/levelstat_alexnesovic:${{ github.sha }}
